// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4P6modcJjOGPiEg5pFK6h9-fGou-T35M',
    appId: '1:212946602101:web:f45c65f3b1d41a0fd4503c',
    messagingSenderId: '212946602101',
    projectId: 'hostel-complaint-app-2c465',
    authDomain: 'hostel-complaint-app-2c465.firebaseapp.com',
    storageBucket: 'hostel-complaint-app-2c465.firebasestorage.app',
    measurementId: 'G-X40TK2ESK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2EzjPedSinQ_mbi0Uf4KmvfzPyUdbgE',
    appId: '1:212946602101:android:03550c7540516321d4503c',
    messagingSenderId: '212946602101',
    projectId: 'hostel-complaint-app-2c465',
    storageBucket: 'hostel-complaint-app-2c465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_utWIWFFu5dSMkXkAhh4EcYqnCuO8tU',
    appId: '1:212946602101:ios:1c3ff3c7bfb89971d4503c',
    messagingSenderId: '212946602101',
    projectId: 'hostel-complaint-app-2c465',
    storageBucket: 'hostel-complaint-app-2c465.firebasestorage.app',
    iosBundleId: 'com.example.hostelComplaintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_utWIWFFu5dSMkXkAhh4EcYqnCuO8tU',
    appId: '1:212946602101:ios:1c3ff3c7bfb89971d4503c',
    messagingSenderId: '212946602101',
    projectId: 'hostel-complaint-app-2c465',
    storageBucket: 'hostel-complaint-app-2c465.firebasestorage.app',
    iosBundleId: 'com.example.hostelComplaintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4P6modcJjOGPiEg5pFK6h9-fGou-T35M',
    appId: '1:212946602101:web:7978429a2a94d95ed4503c',
    messagingSenderId: '212946602101',
    projectId: 'hostel-complaint-app-2c465',
    authDomain: 'hostel-complaint-app-2c465.firebaseapp.com',
    storageBucket: 'hostel-complaint-app-2c465.firebasestorage.app',
    measurementId: 'G-MEP9JREKLY',
  );
}
